"""Add separate Jira and Confluence fields to MCP configuration

Revision ID: 09a57f860f0a
Revises: 3bd01025c3aa
Create Date: 2025-08-04 18:01:32.565724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a57f860f0a'
down_revision = '3bd01025c3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jira_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jira_personal_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('jira_ssl_verify', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confluence_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confluence_personal_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confluence_ssl_verify', sa.Boolean(), nullable=True))
        batch_op.alter_column('server_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('personal_access_token',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_configurations', schema=None) as batch_op:
        batch_op.alter_column('personal_access_token',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('server_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('confluence_ssl_verify')
        batch_op.drop_column('confluence_personal_token')
        batch_op.drop_column('confluence_url')
        batch_op.drop_column('jira_ssl_verify')
        batch_op.drop_column('jira_personal_token')
        batch_op.drop_column('jira_url')

    # ### end Alembic commands ###
